"""
Problem Number: 389. Find the Difference
Difficulty Level: Easy
https://leetcode.com/problems/find-the-difference

********************************************************************************

You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a
random position. Return the letter that was added to t.
  
Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
  
Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        ascii_1 = 0
        ascii_2 = 0

        for i in range(len(s)):
            ascii_1 += ord(s[i])
            ascii_2 += ord(t[i])
        ascii_2 += ord(t[-1])

        return chr(ascii_2 - ascii_1)

# Time Complexity: O(n)
# Space Complexity: O(1)
